"""initial migration

Revision ID: 05ddafa0a00c
Revises: 
Create Date: 2024-04-05 11:01:22.006334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ddafa0a00c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_category'))
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('user_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tag'))
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('source_category_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_category_id'], ['source_category.id'], name=op.f('fk_recipe_source_category_id_source_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe'))
    )
    op.create_table('meal_prep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(), nullable=True),
    sa.Column('meal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_meal_prep_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_meal_prep_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_prep'))
    )
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_value', sa.Float(), nullable=True),
    sa.Column('inredient_unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_ingredient_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredient'))
    )
    op.create_table('recipe_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_tag_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_recipe_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_tag'))
    )
    op.create_table('user_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('not_reorder', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_user_recipe_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_recipe_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_recipe'))
    )
    op.create_table('user_recipe_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('user_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_user_recipe_tag_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_recipe_tag_user_id_user')),
    sa.ForeignKeyConstraint(['user_tag_id'], ['user_tag.id'], name=op.f('fk_user_recipe_tag_user_tag_id_user_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_recipe_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe_tag')
    op.drop_table('user_recipe')
    op.drop_table('recipe_tag')
    op.drop_table('recipe_ingredient')
    op.drop_table('meal_prep')
    op.drop_table('recipe')
    op.drop_table('user_tag')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('source_category')
    # ### end Alembic commands ###
