"""add cooked instances table

Revision ID: 96e5ab7d04db
Revises: 2e7b9aed6e33
Create Date: 2025-03-30 18:47:51.909708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e5ab7d04db'
down_revision = '2e7b9aed6e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooked_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_recipe_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('cooked_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_recipe_id'], ['user_recipe.id'], name=op.f('fk_cooked_instance_user_recipe_id_user_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cooked_instance'))
    )
    # op.alter_column('meal_prep', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('meal_prep', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'weekday',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'meal',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'picture',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source_category_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'reference',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'instructions',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'created_by_user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_ingredient', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_unit',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_note',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_tag', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'tag_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('source_category', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('source_category', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_source_category_name'), 'source_category', ['name'])
    # op.alter_column('tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('tag', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_tag_name'), 'tag', ['name'])
    # op.alter_column('user', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('user', 'password_hash',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_user_name'), 'user', ['name'])
    # op.alter_column('user_recipe', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'comments',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe_tag', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'user_tag_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_tag', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_user_tag_name'), 'user_tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_user_tag_name'), 'user_tag', type_='unique')
    # op.alter_column('user_tag', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe_tag', 'user_tag_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe', 'comments',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('uq_user_name'), 'user', type_='unique')
    # op.alter_column('user', 'password_hash',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('uq_tag_name'), 'tag', type_='unique')
    # op.alter_column('tag', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('uq_source_category_name'), 'source_category', type_='unique')
    # op.alter_column('source_category', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('source_category', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_tag', 'tag_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_ingredient', 'ingredient_note',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_unit',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe', 'created_by_user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'instructions',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'reference',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source_category_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'picture',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('meal_prep', 'meal',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'weekday',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_table('cooked_instance')
    # ### end Alembic commands ###
