"""add restaurant models

Revision ID: 96eeb5868c4c
Revises: 7a511b459664
Create Date: 2026-04-24 17:49:19.442678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96eeb5868c4c'
down_revision = '7a511b459664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant')),
    sa.UniqueConstraint('external_id', name=op.f('uq_restaurant_external_id'))
    )
    op.create_table('restaurant_menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_restaurant_menu_item_restaurant_id_restaurant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_menu_item'))
    )
    op.create_table('user_restaurant_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date_eaten', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['restaurant_menu_item.id'], name=op.f('fk_user_restaurant_note_menu_item_id_restaurant_menu_item')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_user_restaurant_note_restaurant_id_restaurant')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_restaurant_note_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_restaurant_note'))
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('user_restaurant_note')
    op.drop_table('restaurant_menu_item')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
