"""add recipe_name to meal_prep

Revision ID: d539c05476a8
Revises: 96eeb5868c4c
Create Date: 2026-04-24 17:53:07.450453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd539c05476a8'
down_revision = '96eeb5868c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_prep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_name', sa.String(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('meal_prep', schema=None) as batch_op:
        batch_op.drop_column('recipe_name')

    # ### end Alembic commands ###
