"""add email to user table

Revision ID: de5fcbf30814
Revises: 96e5ab7d04db
Create Date: 2025-04-06 17:06:59.532785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5fcbf30814'
down_revision = '96e5ab7d04db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('meal_prep', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('meal_prep', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'weekday',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'meal',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'picture',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source_category_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'reference',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'instructions',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'created_by_user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_ingredient', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_unit',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_note',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_tag', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'tag_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.drop_constraint('fk_shopping_list_mealprep_id_meal_prep', 'shopping_list', type_='foreignkey')
    # op.create_foreign_key(op.f('fk_shopping_list_mealprep_id_meal_prep'), 'shopping_list', 'meal_prep', ['mealprep_id'], ['id'], ondelete='CASCADE')
    # op.alter_column('source_category', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('source_category', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_source_category_name'), 'source_category', ['name'])
    # op.alter_column('tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('tag', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_tag_name'), 'tag', ['name'])
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # op.alter_column('user', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('user', 'password_hash',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_user_name'), 'user', ['name'])
    # op.alter_column('user_recipe', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'comments',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe_tag', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'recipe_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'user_tag_id',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('user_tag', 'id',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_tag', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    # op.create_unique_constraint(op.f('uq_user_tag_name'), 'user_tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('uq_user_tag_name'), 'user_tag', type_='unique')
    # op.alter_column('user_tag', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe_tag', 'user_tag_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_recipe', 'comments',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('user_recipe', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('uq_user_name'), 'user', type_='unique')
    # op.alter_column('user', 'password_hash',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('user', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_column('user', 'email')
    # op.drop_constraint(op.f('uq_tag_name'), 'tag', type_='unique')
    # op.alter_column('tag', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('uq_source_category_name'), 'source_category', type_='unique')
    # op.alter_column('source_category', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('source_category', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.drop_constraint(op.f('fk_shopping_list_mealprep_id_meal_prep'), 'shopping_list', type_='foreignkey')
    # op.create_foreign_key('fk_shopping_list_mealprep_id_meal_prep', 'shopping_list', 'meal_prep', ['mealprep_id'], ['id'])
    # op.alter_column('recipe_tag', 'tag_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_tag', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe_ingredient', 'ingredient_note',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_unit',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'ingredient_name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe_ingredient', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('recipe', 'created_by_user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'instructions',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'reference',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'source_category_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'picture',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'name',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('recipe', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('meal_prep', 'meal',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'weekday',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'recipe_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'user_id',
    #            existing_type=sa.Integer(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('meal_prep', 'id',
    #            existing_type=sa.Integer(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
    #            type_=sa.BIGINT(),
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###
