"""add created-by-user in recipes

Revision ID: e873b0dea754
Revises: c1ac4073fa45
Create Date: 2024-04-22 13:11:32.611479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e873b0dea754'
down_revision = 'c1ac4073fa45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_recipe_created_by_user_id_user'), 'recipe', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recipe_created_by_user_id_user'), 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'created_by_user_id')
    # ### end Alembic commands ###
